# baseURL
@baseURL = http://localhost:3000/api/v1
@endpoint = book-rents

###
# Find All Book Inventories
GET {{ baseURL }}/{{ endpoint }}

###
# Find rented books for class by classNum
GET {{ baseURL }}/{{ endpoint }}/1

###
# Find Book rent by classNum and BookId 
GET {{ baseURL }}/{{ endpoint }}/1/dNG7RMrsFqccbCze562zj

###
# Create Book Rent
POST {{ baseURL }}/{{ endpoint }}
Content-Type: application/json
##978-3-1057-5285-2 "dNG7RMrsFqccbCze562zj",

{
    "bookId": "mdx_Ttc-0omJfNWhSIwWL",
    "classNum":1,
    "rentedBy": 3,
    "amount": 10
}

###
# Modify Book Rent By classNum and BookId
PUT {{ baseURL }}/{{ endpoint }}/1/mdx_Ttc-0omJfNWhSIwWL
Content-Type: application/json

{
    "status": "done"
}

###
# Delete Book Rent By classNum and BookId
DELETE {{ baseURL }}/{{ endpoint }}/asda/mdx_Ttc-0omJfNWhSIwWL