# baseURL
@baseURL = http://localhost:3000
@endpoint = book-inventories

###
# Find All Book Inventories
GET {{ baseURL }}/{{ endpoint }}

###
# Find Book Inventory By Isbn
GET {{ baseURL }}/{{ endpoint }}/978-7-8564-7719-4

###
# Create Book Inventory
POST {{ baseURL }}/{{ endpoint }}
Content-Type: application/json
##978-3-1057-5285-2

{
    "isbn": "978-7-8564-7719-4",
    "amount": 50
}

###
# Modify Book Inventory By Isbn
PUT {{ baseURL }}/{{ endpoint }}/978-7-8564-7719-4
Content-Type: application/json

{
    "isbn": "978-7-8564-7719-4",
    "amount": 40
}

###
# Delete Book By Isbn
DELETE {{ baseURL }}/{{ endpoint }}/978-7-8564-7719-4