# baseURL
@baseURL = http://localhost:3000/api/v1
@endpoint = books

###
# Find All Books
GET {{ baseURL }}/{{ endpoint }}

###
# Find Book By Isbn
GET {{ baseURL }}/{{ endpoint }}/978-3-1057-5285-2

###
# Create Book
POST {{ baseURL }}/{{ endpoint }}
Content-Type: application/json
##978-3-1057-5285-2

{
    "isbn": "978-7-8564-7719-4",
    "title": "Random test",
    "description": "Random book description",
    "imageUrl": "https://google.at",
    "publisher": "Random Lmt",
    "createdBy": 3,
    "publishingDate":"2022-09-12T09:34:07.370Z"
}

###
# Modify Book By Isbn
PUT {{ baseURL }}/{{ endpoint }}/978-3-1057-5285-2
Content-Type: application/json

{
    "isbn": "978-3-1057-5285-2",
    "title": "Random test 2",
    "description": "Random book description 2",
    "imageUrl": "https://google.at/2",
    "publisher": "Random Lmt",
    "createdBy": 1
}

###
# Delete Book By Isbn
DELETE {{ baseURL }}/{{ endpoint }}/978-3-1057-5285-2