# baseURL
@baseURL = http://localhost:3000/api/v1
@endpoint = users

###
# Find All Users
GET {{ baseURL }}/{{ endpoint }}

###
# Find User By Id
GET {{ baseURL }}/{{ endpoint }}/1

###
# Create User
POST {{ baseURL }}/{{ endpoint }}
Content-Type: application/json

{
    "email": "example2@email.com",
    "name": "Jessica Harbour",
	"password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/{{ endpoint }}/1
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}

###
# Delete User By Id
DELETE {{ baseURL }}/{{ endpoint }}/2
